In [1]:
import numpy as np

In [10]:
a=np.zeros([9,9])
bases=[]
print(a)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [11]:
#add some bases to a
a[1,5]=1
bases.append([1,5])

In [8]:
a[np.random.choice(9),np.random.choice(9)]

0.0

In [14]:
np.sort(a[1,:])==[1,2,3,4,5,6,7,8,9]

array([False, False, False, False, False, False, False, False, False], dtype=bool)

In [ ]:
def eval(a):
    for row in a:
        if a